# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: expense_api_development

test:
  <<: *default
  database: expense_api_test

production:
  <<: *default
  database: expense_api_production
  username: expense_api
  password: <%= ENV['EXPENSE_API_DATABASE_PASSWORD'] %>
